Content:
    - framework/doc/content
    - modules/fusion/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: Fusion
        repo: https://github.com/idaholab/moose
        home: /modules/fusion
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/fusion
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/fusion/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.sqa: disable
