Content:
    - framework/doc/content
    - modules/fusion/doc/content
    - modules/thermal_hydraulics/doc/content
    - modules/fluid_properties/doc/content
    - modules/heat_conduction/doc/content
    - modules/misc/doc/content
    - modules/navier_stokes/doc/content
    - modules/ray_tracing/doc/content
    - modules/rdg/doc/content
    - modules/solid_properties/doc/content
    - infrastructure:
        root_dir: modules/doc/content
        content:
          - application_usage/command_line_usage.md

Renderer:
    type: MooseDocs.base.MaterializeRenderer

Extensions:
    MooseDocs.extensions.navigation:
        name: MOOSE Fusion Module
        repo: https://github.com/idaholab/moose
        home: /modules/fusion
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/fusion
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/fusion/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.template:
        active: True
    MooseDocs.extensions.sqa: disable
