gcc: "13.3.1"
clang: "19"
minimum_gcc: "9.0.0"
maximum_gcc: "13.3.1"
minimum_clang: "14.0.6"
maximum_clang: "19"
python_default: "3.13"
minimum_python: "3.10"
maximum_python: "3.13"
mpich: "4.3.0"
openmpi: "5.0.7"
petsc: "3.23.4"
apptainer_rockylinux: "8.10"
apptainer_mpich: "4.3.1"
apptainer_gcc: "13.3.1"
default_mpi: "mpich"
python_packages: "packaging pyaml jinja2"
