mpi:
  - mpich
  - openmpi

moose_libmesh:
  - moose-libmesh 2025.08.06 mpich_0
  - moose-libmesh 2025.08.06 openmpi_0

moose_wasp:
  - moose-wasp 2025.07.07

moose_tools:
  - moose-tools 2025.06.26

zip_keys:
  - mpi
  - moose_libmesh
